env:
  browser: true
  commonjs: true
  es2020: true
extends:
<<<<<<< HEAD
  - 'plugin:react/recommended'
  - google
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
plugins:
  - react
=======
  - google
parserOptions:
  ecmaVersion: 11
>>>>>>> master
rules: {}
